### PR TITLE
Bug: Unspecific error messages for MedCon and Allergy commands when input is not alphanumeric

### LINKED ISSUE #237: Bug: Error message for `addAllergy` command is not specific
Steps to reproduce bug:
1. Use command `addAllergy i/s1234567a al/\`
2. Error message says `Invalid allergy format`

image

Possible fix:
1. Message shown could specify that allergy name should be alphanumeric and not contain special characters

Right now this is the code for `parseAllergy` which is similar to `parseMedCon`:
image

This is the Allergy class, it contains a few messages that are not being used in the parser, do note that the `checkArgument` methods used in the Allergy class are just in case an `Allergy` is able to be constructed without being parsed. In that sense, your error handling/messages in `Allergy` class should be similar to in `parseAllergy` in `ParserUtil`.

Additionally, there exist a `isValidAllergyName` and `isValidMedConName` that are only being used in the constructor of the class instead of being used as valdiators for the parser methods in `ParserUtil`
image

### PR DESCRIPTION
**Pull request by TechRaj**
Fixes #237 

This PR addresses an issue where the error messages were not specific when a non-alphanumeric medical condition or allergy name was provided. I've updated the `parseAllergy` and `parseMedCon` methods to return more informative error messages, clearly indicating that MedCon and Allergy names must be alphanumeric.

#### Changes Made:
- **parseMedCon** and **parseAllergy** methods have been updated to provide a detailed message for non-alphanumeric inputs.
  
Attached below are screenshots showing the new error messages for your visual review:

Screenshot 2024-10-29 at 15 58 02
Screenshot 2024-10-29 at 15 58 29

### CODE REVIEW

**Review by PresleyChew — CHANGES_REQUESTED** [review]
Nit, change to 'name' instead of 'names' as its singular instance of name.

File: src/main/java/seedu/address/logic/Messages.java [hunk 1]
```diff
@@ -21,7 +21,7 @@ public class Messages {
                 "Multiple values specified for the following single-valued field(s): ";
     public static final String MESSAGE_CONSTRAINTS_LENGTH =
             "length should not exceed the limit of 30 characters";
-    public static final String MESSAGE_CONSTRAINTS_ALPHANUMERIC_LENGTH = " names should be alphanumeric and not "
+    public static final String MESSAGE_CONSTRAINTS_ALPHANUMERIC_LENGTH = "names should be alphanumeric and not "
```
Comment (hweinian) [inline src/main/java/seedu/address/logic/Messages.java:24]: Should be name instead of names. Suppose its names, it would indicate name1 + name2 + name3 should be in alphanumeric and not exceed 30 characters.

**Review by hweinian — CHANGES_REQUESTED** [review]

**Review by yong-zhuo — APPROVED** [review]
