### PR TITLE
Fix `findMedCon` error message 

### LINKED ISSUE #332: Fix inconsistencies for `find` and `findMedCon` command
* `findMedCon` command usage should show `Parameters: KEYWORD [MORE_KEYWORDS]...` , similar to `find` command
* UG should be updated to show `find KEYWORD [MORE_KEYWORDS]..` and `findMedCon KEYWORD [MORE_KEYWORDS]..` as well

### PR DESCRIPTION
**Pull request by yong-zhuo**
fixes #332

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/FindCommand.java [hunk 1]
```diff
@@ -17,7 +17,7 @@ public class FindCommand extends Command {
     public static final String COMMAND_WORD_INSENSITIVE = "find";
 
     public static final String MESSAGE_USAGE = COMMAND_WORD + ": Finds all patients whose names contain any of "
-            + "the specified keywords (case-insensitive) and displays them as a list with index numbers.\n"
+            + "the specified keywords (case-insensitive) and displays them.\n"
```
Comment (TechRaj) [inline src/main/java/seedu/address/logic/commands/FindCommand.java:20]: good catch

File: src/main/java/seedu/address/logic/commands/FindMedConCommand.java [hunk 2]
```diff
@@ -17,9 +17,8 @@ public class FindMedConCommand extends Command {
     public static final String COMMAND_WORD_INSENSITIVE = "findmedcon";
 
     public static final String MESSAGE_USAGE = COMMAND_WORD + ": Finds all patients with medical conditions that "
-            + "contains the specified keywords (case-insensitive) and displays them as a list with index numbers.\n"
-            + "Parameters: "
-            + "KEYWORD [MORE KEYWORDS]\n"
+            + "contains the specified keywords (case-insensitive) and displays them.\n"
+            + "Parameters: KEYWORD [MORE KEYWORDS]...\n"
```
Comment (TechRaj) [inline src/main/java/seedu/address/logic/commands/FindMedConCommand.java:21]: Actually adding the params on a new line is more inline with the other command usage format messages

File: src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java [hunk 3]
```diff
@@ -156,6 +157,16 @@ public void toModelType_invalidDateOfBirthFutureDate_throwsIllegalValueException
         assertThrows(IllegalValueException.class, expectedMessage, person::toModelType);
     }
 
+    @Test
+    public void toModelType_invalidDateOfBirthInvalidDate_throwsIllegalValueException() {
+        JsonAdaptedPerson person =
+                new JsonAdaptedPerson(VALID_NAME, VALID_PHONE, VALID_EMAIL, VALID_ADDRESS,
+                        INVALID_DATE_OF_BIRTH_INVALID_DATE, VALID_GENDER, VALID_NRIC, VALID_ALLERGIES, VALID_PRIORITY,
+                        VALID_APPOINTMENTS, VALID_MEDCON);
+        String expectedMessage = DateOfBirth.MESSAGE_CONSTRAINTS_DATE_DOES_NOT_EXIST;
```
Comment (TechRaj) [inline src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java:166]: good testing!

**Review by TechRaj — CHANGES_REQUESTED** [review]
LGTM. Just one nit to maintain error message consistency
