### PR TITLE
Fix delete and add medical condition

### LINKED ISSUE #133: Bug: Able to add/delete empty medical condition
When adding/deleting medical conditions, user is able to not input the `c/` field and it will result in the app sending a success message

### PR DESCRIPTION
**Pull request by hweinian**
fixes #133 #136 

It will fix the delete empty parameter bug. Empty fields will now display an error

add medical condition can now be added even after filtering person list and will display an error when nric field is empty.

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/AddMedConCommand.java [hunk 1]
```diff
@@ -49,25 +49,24 @@ public AddMedConCommand(Nric nric, Set<MedCon> medCons) {
...
-                        throw new CommandException(String.format(MESSAGE_DUPLICATE_MEDCON, medCon.value));
-                    }
+        Person person = model.fetchPersonIfPresent(new NricMatchesPredicate(nric))
+                .orElseThrow(() -> new CommandException(PATIENT_DOES_NOT_EXIST));
+        if (person.getNric().equals(this.nric)) {
+            Set<MedCon> updatedMedConSet = new HashSet<>(person.getMedCons());
+            // check for duplicates
+            for (MedCon medCon : medCons) {
+                if (!updatedMedConSet.add(medCon)) {
+                    throw new CommandException(String.format(MESSAGE_DUPLICATE_MEDCON, medCon.value));
```
Comment (yong-zhuo) [inline src/main/java/seedu/address/logic/commands/AddMedConCommand.java:59]: Fix looks good 👍🏻

**Review by yong-zhuo — APPROVED** [review]
