### PR TITLE
Fix string formatting issues

### LINKED ISSUE #141: String formatting issues in `Add` command and `FindMedCon` command

### PR DESCRIPTION
**Pull request by yong-zhuo**
fixes #141 

Fix string formatting issues in add command and findmedcon command

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/FindMedConCommand.java [hunk 1]
```diff
@@ -15,7 +15,7 @@
 public class FindMedConCommand extends Command {
     public static final String COMMAND_WORD = "findMedCon";
 
-    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Finds all patients with medical conditions that"
+    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Finds all patients with medical conditions that "
```
Comment (hweinian) [inline src/main/java/seedu/address/logic/commands/FindMedConCommand.java:18]: good fix

**Review by hweinian — APPROVED** [review]
