### PR TITLE
Fix bug in add allergy

### LINKED ISSUE #137: Bug: unable to add allergy when list is filtered
currently, we are unable to add allergy when the list is filtered

### PR DESCRIPTION
**Pull request by hweinian**
fixes #137 

This will resolve the bug where you are unable to add allergy when the list is filtered

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/AddAllergyCommand.java [hunk 1]
```diff
@@ -51,27 +51,28 @@ public AddAllergyCommand(Nric nric, Set<Allergy> allergies) {
...
-                    }
+        Person person = model.fetchPersonIfPresent(new NricMatchesPredicate(nric))
+                .orElseThrow(() -> new CommandException(PATIENT_DOES_NOT_EXIST));
+
+        if (person.getNric().equals(this.nric)) {
+            Set<Allergy> updatedAllergiesSet = new HashSet<>(person.getAllergies());
+            // check for duplicates
+            for (Allergy allergy : allergies) {
+                if (!updatedAllergiesSet.add(allergy)) {
+                    throw new CommandException(String.format(MESSAGE_DUPLICATE_ALLERGY, allergy.toString()));
```
Comment (yong-zhuo) [inline src/main/java/seedu/address/logic/commands/AddAllergyCommand.java:62]: Good fix, good check for duplicate allergies too

**Review by yong-zhuo — APPROVED** [review]
