### PR TITLE
Bug: Non-standardised error messages for medical condition and allergy commands

### LINKED ISSUE #233: Bug: Invalid command format message in deleteAllergy to be changed
image

Currently, the invalid command format mention that it will remove allergy form a patient in the address book. I think it would be better if we specify it to Medibase3. Additionally, parameter should be on a new line, and it should be i/NRIC. This is to ensure consistency between other commands as other command follow this format.
However, if we do make such changes, it needs to be consistent and done throughout.

### PR DESCRIPTION
**Pull request by TechRaj**
Fixes #233 

The invalid command format error messages in `addMedCon`, `delMedCon`, `addAllergy`, and `delAllergy` were inconsistent with the style used by other commands. To maintain a uniform user experience, I updated these messages to match the consistent format used throughout the main functions.

Below are the screenshots of the updated error messages for your review:

1. **AddMedCon Command Error:**
Screenshot 2024-10-29 at 15 05 41

2. **DelMedCon Command Error:**
Screenshot 2024-10-29 at 15 08 01

3. **AddAllergy Command Error:**
Screenshot 2024-10-29 at 15 07 37

4. **DelAllergy Command Error:**
Screenshot 2024-10-29 at 15 06 43

### CODE REVIEW

**Review by PresleyChew — COMMENTED** [review]
Raj , the square bracket indicates optional parameter. If it is compulsory parameter square bracket is to be omitted. Able to take reference from feature list.

File: src/main/java/seedu/address/logic/commands/AddAllergyCommand.java [hunk 1]
```diff
@@ -23,9 +23,10 @@ public class AddAllergyCommand extends Command {
 
     public static final String COMMAND_WORD = "addAllergy";
 
-    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Adds allergy to the patient in the address book. "
-            + "Parameters: NRIC (must be a valid NRIC in the system) "
-            + "[" + PREFIX_ALLERGY + "Allergy]...\n"
+    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Adds allergy to the patient in MediBase3. \n"
+            + "Parameters: "
+            + PREFIX_NRIC + "NRIC "
+            + "[" + PREFIX_ALLERGY + "ALLERGY]...\n"
```
Comment (yong-zhuo) [inline src/main/java/seedu/address/logic/commands/AddAllergyCommand.java:29]: No need to have the brackets since its not optional, same for `c/CONDITION...`

**Review by yong-zhuo — CHANGES_REQUESTED** [review]
