### PR TITLE
Bug Fix for Priority being unable to be assigned when person not in view

### LINKED ISSUE #134: Bug Fix for inability to assign Priority when Person is not in the view
Currently there is a bug where if we listPrio or findNric and we proceed to assignPriority to person that is not listed by the aforementioned commands, there will be an error.

### PR DESCRIPTION
**Pull request by PresleyChew**
fixes #134

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/PriorityCommand.java [hunk 1]
```diff
@@ -48,28 +48,34 @@ public PriorityCommand(Nric nric, Priority priority) {
...
+            Person editedPerson = new Person(
+                    person.getName(), person.getPhone(), person.getEmail(),
+                    person.getNric(), person.getAddress(), person.getDateOfBirth(),
+                    person.getGender(), person.getAllergies(), priority, person.getAppointments(),
+                    person.getMedCons());
+            model.setPerson(person, editedPerson);
+            model.updateFilteredPersonList(Model.PREDICATE_SHOW_ALL_PERSONS);
+            return new CommandResult(generateSuccessMessage(editedPerson));
+        } else {
+            throw new CommandException(PATIENT_DOES_NOT_EXIST);
```
Comment (yong-zhuo) [inline src/main/java/seedu/address/logic/commands/PriorityCommand.java:77]: Good fix

**Review by yong-zhuo — APPROVED** [review]
Overall LGTM

File: src/main/java/seedu/address/logic/commands/PriorityCommand.java (hunk 1 above)
Comment (hweinian) [inline src/main/java/seedu/address/logic/commands/PriorityCommand.java:77]: good fix

**Review by hweinian — APPROVED** [review]
