### PR TITLE
Bug: Error message showing wrong usage for edit command

### LINKED ISSUE #221: Bug: Error message showing wrong usage for `edit` command
Steps to reproduce bug:
1. Use command `edit s1234567a`
2. Error message indicates that prefix `al/` is supported when it is not

image

Possible fix:
1. Fix the message usage for `edit` command

### PR DESCRIPTION
**Pull request by hweinian**
fixes #221 

image

What changed:
- Edit invalid command format message
- remove tokenizing to resolve the bug for wrong usage

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -45,7 +44,7 @@ public class EditCommand extends Command {
 
     public static final String COMMAND_WORD = "edit";
 
-    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Edits the details of the patient identified "
+    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Edits the details of the patient identified. "
```
Comment (PresleyChew) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:47]: Good catch here!

**Review by PresleyChew — APPROVED** [review]
LGTM
