### PR TITLE
Fix Error Message For DelAppointmentCommand

### LINKED ISSUE #139: Incorrect Success Message formatting for DelAppointment commandt
image

### PR DESCRIPTION
**Pull request by yadobler**
fixes #139

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/DeleteApptCommand.java [hunk 1]
```diff
@@ -86,8 +86,8 @@ public CommandResult execute(Model model) throws CommandException {
                     + "appointment: " + targetAppt);
         model.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS);
         return new CommandResult(String.format(MESSAGE_DELETE_APPOINTMENT_SUCCESS_2S,
-                                               personToEdit.getNric().value,
-                                               apptToDelete));
+                                               apptToDelete,
+                                               personToEdit.getNric().value));
     }
```
Comment (hweinian) [inline src/main/java/seedu/address/logic/commands/DeleteApptCommand.java:91]: LGTM

File: src/test/java/seedu/address/logic/commands/DeleteApptCommandTest.java [hunk 2]
```diff
@@ -74,7 +74,7 @@ public void execute_allFieldsSpecified_success() {
                                                    .build();
         expectedModel.setPerson(targetPerson, expectedPerson);
         String expectedMessage = String.format(DeleteApptCommand.MESSAGE_DELETE_APPOINTMENT_SUCCESS_2S,
-                                               nric.value, apptToDelete.toString());
+                                               apptToDelete.toString(), nric.value);
```
Comment (hweinian) [inline src/test/java/seedu/address/logic/commands/DeleteApptCommandTest.java:77]: should fix ordering issue

**Review by hweinian — APPROVED** [review]

File: src/main/java/seedu/address/logic/commands/DeleteApptCommand.java [hunk 3]
```diff
@@ -50,7 +50,7 @@ public class DeleteApptCommand extends Command {
             + PREFIX_DATE + "2024-10-24 "
             + PREFIX_TIMEPERIOD + "1235-1400";
 
-    public static final String MESSAGE_DELETE_APPOINTMENT_SUCCESS_2S = "Deleted Appointment %s for Patient %s";
+    public static final String MESSAGE_DELETE_APPOINTMENT_SUCCESS_2S = "Deleted Appointment \"%s\" for Patient %s";
```
Comment (yong-zhuo) [inline src/main/java/seedu/address/logic/commands/DeleteApptCommand.java:53]: Fix looks good 👍🏻

**Review by yong-zhuo — APPROVED** [review]
