### PR TITLE
Remove tag from project

### LINKED ISSUE #162: Migrate Tags to Allergy
Based on regex search `[tT]ag[s]?\b`, there are discrepancies between the `tag` and `allergy` naming:

```
Targets
    Occurrences of '[tT]ag[s]?\b' in Directory /home/yukna/Documents/School/AY2425/CS2103T/repos/tp with mask '*.java'
Found occurrences in Directory /home/yukna/Documents/School/AY2425/CS2103T/repos/tp with mask '*.java'  (51 usages found)
    AddAllergyCommandTest.java  (9 usages found)
        51 Set<Allergy> expectedTags = new HashSet<>();
        52 expectedTags.add(new Allergy(allergy));
        53 expectedTags.addAll(ALICE.getAllergies());
        59 assertEquals(expectedTags, alice.getAllergies());
        65 Set<Allergy> aliceTags = ALICE.getAllergies();
        67 Set<Allergy> bobTags = BOB.getAllergies();
        68 AddAllergyCommand addAliceAllergyCommand = new AddAllergyCommand(aliceNric, aliceTags);
        69 AddAllergyCommand addBobCommand = new AddAllergyCommand(bobNric, bobTags);
        74 AddAllergyCommand addAliceAllergyCommandCopy = new AddAllergyCommand(aliceNric, aliceTags);
    AllergyTest.java  (1 usage found)
        22 // null tag name
    ArgumentTokenizerTest.java  (1 usage found)
        58 String argsString = "  some random string /t tag with leading and trailing spaces ";
    CommandTestUtil.java  (3 usages found)
        115 public static final String INVALID_ALLERGY_DESC = " " + PREFIX_ALLERGY + "shellfish*"; // '*' not allowed in tags
        177 .withTags(VALID_ALLERGY_MILK).build();
        181 .withTags(VALID_ALLERGY_SOYBEANS, VALID_ALLERGY_MILK).build();
    EditCommand.java  (2 usages found)
        117 Set<Allergy> updatedTags = editPersonDescriptor.getAllergies().orElse(personToEdit.getAllergies());
        124 updatedGender, updatedTags, updatedPriority, updatedAppointments, updatedMedCons);
    EditCommandParserTest.java  (5 usages found)
        102 // while parsing {@code PREFIX_ALLERGY} alone will reset the tags of the {@code Person} being edited,
        123 .withTags(VALID_ALLERGY_SOYBEANS, VALID_ALLERGY_MILK).build();
        167 // tags
        169 descriptor = new EditPersonDescriptorBuilder().withTags(VALID_ALLERGY_MILK).build();
        211 EditPersonDescriptor descriptor = new EditPersonDescriptorBuilder().withTags().build();
    EditPersonDescriptorBuilder.java  (1 usage found)
        109 public EditPersonDescriptorBuilder withTags(String... allergies) {
    EditPersonDescriptorTest.java  (3 usages found)
        56 // different tags -> returns false
        57 editedAmy = new EditPersonDescriptorBuilder(DESC_AMY).withTags(VALID_ALLERGY_SOYBEANS).build();
        68 + editPersonDescriptor.getAddress().orElse(null) + ", tags="
    JsonAdaptedMedCon.java  (3 usages found)
        19 * Constructs a {@code JsonAdaptedTag} with the given {@code tagName}.
        27 * Converts a given {@code Tag} into this class for Jackson use.
        39 * Converts this Jackson-friendly adapted tag object into the model's {@code MedCon} object.
    JsonAdaptedPersonTest.java  (5 usages found)
        37 private static final String INVALID_TAG = "#friend";
        205 List<JsonAdaptedAllergy> invalidTags = new ArrayList<>(VALID_ALLERGIES);
        206 invalidTags.add(new JsonAdaptedAllergy(INVALID_TAG));
        206 invalidTags.add(new JsonAdaptedAllergy(INVALID_TAG));
        209 VALID_DATE_OF_BIRTH, VALID_GENDER, invalidTags, VALID_PRIORITY, VALID_APPOINTMENTS,
    ParserUtilTest.java  (6 usages found)
        252 public void parseAllergy_validValueWithoutWhitespace_returnsTag() throws Exception {
        253 Allergy expectedTag = new Allergy(VALID_ALLERGY_1);
        254 assertEquals(expectedTag, ParserUtil.parseAllergy(VALID_ALLERGY_1));
        258 public void parseAllergy_validValueWithWhitespace_returnsTrimmedTag() throws Exception {
        260 Allergy expectedTag = new Allergy(VALID_ALLERGY_1);
        261 assertEquals(expectedTag, ParserUtil.parseAllergy(tagWithWhitespace));
    PersonBuilder.java  (9 usages found)
        41 private Set<Allergy> tags;
        57 tags = new HashSet<>();
        74 tags = new HashSet<>(personToCopy.getAllergies());
        98 * Parses the {@code tags} into a {@code Set<Tag>} and set it to the {@code Person} that we are building.
        98 * Parses the {@code tags} into a {@code Set<Tag>} and set it to the {@code Person} that we are building.
        100 public PersonBuilder withAllergies(String ... tags) {
        101 this.tags = SampleDataUtil.getAllergiesSet(tags);
        101 this.tags = SampleDataUtil.getAllergiesSet(tags);
        175 return new Person(name, phone, email, nric, address, dob, gender, tags, priority, appointments, medCons);
    PersonUtil.java  (3 usages found)
        70 Set<Allergy> tags = descriptor.getAllergies().get();
        71 if (tags.isEmpty()) {
        74 tags.forEach(s -> sb.append(PREFIX_ALLERGY).append(s.allergyName).append(" "));
```

### PR DESCRIPTION
**Pull request by yadobler**
fixes #162 

This does not touch the `.md` files, in particular `DeveloperGuide.md` as that will be handled when updating the DG.

### CODE REVIEW

File: src/test/java/seedu/address/logic/parser/EditCommandParserTest.java [hunk 1]
```diff
@@ -187,7 +187,7 @@ public void parse_multipleRepeatedFields_failure() {
 
         assertParseFailure(parser, userInput, Messages.getErrorMessageForDuplicatePrefixes(PREFIX_PHONE));
 
-        // mulltiple valid fields repeated
```
Comment (yong-zhuo) [inline src/test/java/seedu/address/logic/parser/EditCommandParserTest.java:190]: Good catch on this typo 👍🏻

**Review by yong-zhuo — APPROVED** [review]
LGTM overall

**Review by PresleyChew — APPROVED** [review]
LGTM
